### ISSUE TITLE
AWS needs configuring in karpenter_deployment.yaml

### ISSUE THREAD

**Issue by the-archbishop** [the-archbishop/joke-fetcher#1]
kubectl logs -n karpenter -l app=karpenter
{"level":"ERROR","time":"2024-12-13T03:18:53.701Z","logger":"controller","message":"ec2 api connectivity check failed","commit":"a2875e3","error":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}

```
env:
  - name: AWS_ACCESS_KEY_ID
    value: "<access-key-id>"
  - name: AWS_SECRET_ACCESS_KEY
    value: "<secret-access-key>"
```
